name: Android CI - Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', 'java-version': 17 }
      - name: Build
        run: |
          chmod +x ./gradlew || true
          ./gradlew assembleDebug --no-daemon
      - uses: actions/upload-artifact@v4
        with: { name: app-debug-apk, path: app/build/outputs/apk/debug/app-debug.apk }
